config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  get 'welcome/index'
  resources :users do
    resources :fishing_reports
  end
  root to: 'welcome#index'
end

app/models/fish.rb
class Fish < ActiveRecord::Base
  belongs_to :user
  belongs_to :fishing_report
  belongs_to :fly
end

app/models/fishing_report.rb
class FishingReport < ActiveRecord::Base
  belongs_to :user
  has_many :flies, dependent: :destroy
  has_many :fish
  has_many :hatches, dependent: :destroy
  validates :user_id, presence: true
  validates :date, presence: true
  validates :title, presence: true

  default_scope -> { order(date: :desc) }

  accepts_nested_attributes_for :fish, reject_if: :all_blank
  accepts_nested_attributes_for :flies, reject_if: :all_blank  
  accepts_nested_attributes_for :hatches, reject_if: :all_blank

end

app/models/fly.rb
class Fly < ActiveRecord::Base
  belongs_to :user
  belongs_to :fishing_report
  has_many :fish
end

app/models/hatch.rb
class Hatch < ActiveRecord::Base
  belongs_to :user
  belongs_to :fishing_report
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :confirmable
  has_many :fishing_reports, dependent: :destroy
  has_many :flies, dependent: :destroy
  has_many :fish, dependent: :destroy
  has_many :hatches, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
end

app/controllers/fish_controller.rb
class FishController < ApplicationController
end

app/controllers/fishing_reports_controller.rb
class FishingReportsController < ApplicationController
  def show
    @fishing_report = FishingReport.find(params[:id])
    @fish = @fishing_report.fish.all
    @flies = @fishing_report.flies.all
    @hatches = @fishing_report.hatches.all
  end

  def new
    @fishing_report = current_user.fishing_reports.new
  end

  def create
    @fishing_report = current_user.fishing_reports.build(fishing_report_params)
    if @fishing_report.save
      flash[:notice] = "Fishing Report created!"
    end
    redirect_to user_path(current_user)
  end

  private

  def fishing_report_params
    params.require(:fishing_report).permit(:title, :date, :location, :body_of_water, :story, :weather, :air_temp, :water_flow, :visibility, :water_temp, :rod_used, :line_used, :leader_used, :tippet_used, :best_time_of_day, :best_water_type, :advice, :other_notes, hatches_attributes: [:insect_type, :time_of_day, :description], flies_attributes: [:name, :fly_type, :size, :tied_yourself, :notes], fish_attributes: [:species, :gps, :length, :weight, :story]  )
  end
end

app/controllers/flies_controller.rb
class FliesController < ApplicationController
end

app/controllers/hatches_controller.rb
class HatchesController < ApplicationController
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:username)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @fishing_reports = @user.fishing_reports.all
  end

  def update
    if current_user.update_attributes(user_params)
     flash[:notice] = "User information updated"
   else
     flash[:error] = "Invalid user information"
   end
    redirect_to user_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :about_me)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fish_helper.rb
module FishHelper
end

app/helpers/fishing_report_helper.rb
module FishingReportHelper
end

app/helpers/flies_helper.rb
module FliesHelper
end

app/helpers/form_helper.rb
module FormHelper
  def setup_fishing_report(fishing_report)
    3.times { fishing_report.hatches.build }
    3.times { fishing_report.flies.build }
    3.times { fishing_report.fish.build }
    fishing_report
  end
end

app/helpers/hatches_helper.rb
module HatchesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?size=#{size}"
    link_to image_tag(gravatar_url, alt: user.username, class: "gravatar"), 'https://en.gravatar.com/emails/', target: '_blank'
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/fish/_fish.html.erb
<li class='fish' id="fish-<%= fish.id %>">
  <b>Species:</b> <%= fish.species %> -
  <b>Length:</b> <%= fish.length %> Inches -
  <b>Weight:</b> <%= fish.weight %> Pounds
  <img src = '<%= fish.gps %>'/>
</li>

app/views/fishing_reports/_fishing_report.html.erb
<li id="fishing-report-<%= fishing_report.id %>">
  <span class="content"><%= link_to fishing_report.title, user_fishing_report_path(fishing_report.user, fishing_report) %> - </span>
  <span class="report-date">
    <%= fishing_report.date.to_formatted_s(:long) %>
  </span>
</li>

app/views/fishing_reports/new.html.erb
<div class='fishing-report-form'>
  <%= form_for ([current_user, setup_fishing_report(@fishing_report)]) do |f| %>
    <h2>New Report</h2>
    <div class="form-group">
      <%= f.text_field :title, class: 'form-control', placeholder: "Title of Report" %>
    </div>
    <div class="form-group">
      <%= f.date_field :date, class: 'form-control', placeholder: "Date Fished" %>
    </div>
    <div class="form-group">
      <%= f.text_field :location, class: 'form-control', placeholder: "Geographic Location" %>
    </div>
    <div class="form-group">
      <% body_of_water_options = ['River', 'Lake', 'Ocean', 'Stream', 'Creek', 'Sea', 'Bay', 'Ocean Shore'] %>
      <%= f.select :body_of_water, body_of_water_options, {}, class: 'form-control'  %>
    </div>
    <div class="form-group">
      <%= f.text_area :story, rows: 8, class: 'form-control', placeholder: "Story" %>
    </div>

    <h3>Conditions</h3>
    <div class="form-group">
      <% weather_options = ['Sunny', 'Partly Cloudy', 'Overcast', 'Light Rain', 'Heavy Rain', 'Snow', 'Foggy'] %>
      <%= f.select :weather, weather_options, {}, class: 'form-control'  %>
    </div>
    <div class="form-group">
      <%= f.text_field :air_temp, class: 'form-control', placeholder: "Air Temperature °F" %>
    </div>
    <div class="form-group">
      <%= f.text_field :water_flow, class: 'form-control', placeholder: "Water Flow" %>
    </div>
    <div class="form-group">
      <%= f.text_field :visibility, class: 'form-control', placeholder: "Water Visibility" %>
    </div>
    <div class="form-group">
      <%= f.text_field :water_temp, class: 'form-control', placeholder: "Water Temperature °F" %>
    </div>

    <h3>Hatches</h3>
    <%= f.fields_for :hatches do |ff| %>
      <div class="form-group">
        <%= ff.text_field :insect_type, class: 'form-control', placeholder: "Insect Species" %>
      </div>
      <div class="form-group">
        <%= ff.text_field :time_of_day, class: 'form-control', placeholder: "Time of Day" %>
      </div>
      <div class="form-group">
        <%= ff.text_field :description, class: 'form-control', placeholder: "Description" %>
      </div>
    <% end %>

    <h3>Equipment</h3>
    <div class="form-group">
      <%= f.text_field :rod_used, class: 'form-control', placeholder: "Rod Used" %>
    </div>
    <div class="form-group">
      <%= f.text_field :line_used, class: 'form-control', placeholder: "Line Used" %>
    </div>
    <div class="form-group">
      <%= f.text_field :leader_used, class: 'form-control', placeholder: "Leader Used" %>
    </div>
    <div class="form-group">
      <%= f.text_field :tippet_used, class: 'form-control', placeholder: "Tippet Used" %>
    </div>

    <h3>Flies Used</h3>
    <%= f.fields_for :flies do |ff| %>
      <div class="form-group">
        <%= ff.text_field :name, class: 'form-control', placeholder: "Fly Name" %>
      </div>
      <div class="form-group">
        <% fly_types = ['Dry', 'Nymph', 'Streamer'] %>
        <%= ff.select :fly_type, fly_types, {}, class: 'form-control'  %>
      </div>
      <div class="form-group">
        <%= ff.text_field :size, class: 'form-control', placeholder: "Size" %>
      </div>
      <div class="form-group">
        <%= ff.text_field :notes, class: 'form-control', placeholder: "Notes" %>
      </div>
      <div>
        <%= label_tag :tied_yourself, "Tied Self" %>
        <%= check_box_tag(:tied_yourself, true, false, class: "checkbox") %>
      </div>
      <% end %>

    <h3>Fish Caught</h3>
    <%= f.fields_for :fish do |ff| %>
      <div class="form-group">
        <%= ff.text_field :species, class: 'form-control', placeholder: "Fish Species" %>
      </div>
      <div class="form-group">
        <%= ff.text_field :length, class: 'form-control', placeholder: "Length" %>
      </div>
      <div class="form-group">
        <%= ff.text_field :gps, class: 'form-control', placeholder: "Image URL" %>
      </div>
    <% end %>

    <h3>Advice</h3>
    <div class="form-group">
      <%= f.text_field :best_time_of_day, class: 'form-control', placeholder: "Best Time of Day to Fish" %>
    </div>
    <div class="form-group">
      <%= f.text_field :best_water_type, class: 'form-control', placeholder: "Best Water Feature to Fish" %>
    </div>
    <div class="form-group">
      <%= f.text_area :advice, rows: 8, class: 'form-control', placeholder: "Advice" %>
    </div>
    <div class="form-group">
      <%= f.text_area :other_notes, rows: 8, class: 'form-control', placeholder: "Other Notes" %>
    </div>

    <%= f.submit "Save", class: 'btn btn-success' %>
  <% end %>
</div>

app/views/fishing_reports/show.html.erb
<h1><%= @fishing_report.title %></h1>
<h4><%= @fishing_report.date.to_formatted_s(:long) %></h4>

<ul>
  <% if @fishing_report.location && @fishing_report.location != '' %><li><b>Location:</b> <%= @fishing_report.location %></li><% end %>
  <% if @fishing_report.gps && @fishing_report.gps != '' %><li><b>GPS Location: </b><%= @fishing_report.gps %></li><% end %>
  <% if @fishing_report.body_of_water && @fishing_report.body_of_water != '' %><li><b>Type of Body of Water:</b> <%= @fishing_report.body_of_water %></li><% end %>
  <% if @fishing_report.story && @fishing_report.story != '' %><li><b>Story: </b><%= @fishing_report.story %></li><% end %>
</ul>

<div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Conditions
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in" role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        <ul>
          <% if @fishing_report.weather && @fishing_report.weather != '' %><li><b>Weather:</b> <%= @fishing_report.weather %></li><% end %>
          <% if @fishing_report.air_temp && @fishing_report.air_temp != '' %><li><b>Air Temp: </b><%= @fishing_report.air_temp %> °F</li><% end %>
          <% if @fishing_report.water_flow && @fishing_report.water_flow != '' %><li><b>Water Flow: </b><%= @fishing_report.water_flow %></li><% end %>
          <% if @fishing_report.visibility && @fishing_report.visibility != '' %><li><b>Water Visibility:</b> <%= @fishing_report.visibility %></li><% end %>
          <% if @fishing_report.water_temp && @fishing_report.water_temp != '' %><li><b>Water Temp: </b><%= @fishing_report.water_temp %> °F</li><% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Hatches
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
      <div class="panel-body">
       <ul>
        <%= render @hatches %>
      </ul>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          Equipment
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
      <div class="panel-body">
       <ul>
          <% if @fishing_report.rod_used && @fishing_report.rod_used != '' %><li><b>Rod Used: </b><%= @fishing_report.rod_used %></li><% end %>
          <% if @fishing_report.line_used && @fishing_report.line_used != '' %><li><b>Line Used: </b><%= @fishing_report.line_used %></li><% end %>
          <% if @fishing_report.leader_used && @fishing_report.leader_used != '' %><li><b>Leader Used: </b><%= @fishing_report.leader_used %></li><% end %>
          <% if @fishing_report.tippet_used && @fishing_report.tippet_used != '' %><li><b>Tippet Used: </b><%= @fishing_report.tippet_used %></li><% end %>
        </ul>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingFour">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
          Flies Used
        </a>
      </h4>
    </div>
    <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
      <div class="panel-body">
       <ul>
         <%= render @flies %>
        </ul>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingFive">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFive" aria-expanded="false" aria-controls="collapseFive">
          Fish Caught
        </a>
      </h4>
    </div>
    <div id="collapseFive" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFive">
      <div class="panel-body">
       <ul>
          <%= render @fish %>
        </ul>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingSix">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseSix" aria-expanded="false" aria-controls="collapseSix">
          Advice
        </a>
      </h4>
    </div>
    <div id="collapseSix" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingSix">
      <div class="panel-body">
       <ul>
          <% if @fishing_report.best_time_of_day && @fishing_report.best_time_of_day != '' %><li><b>Best Time of Day to Fish:</b> <%= @fishing_report.best_time_of_day %></li><% end %>
          <% if @fishing_report.best_water_type && @fishing_report.best_water_type != '' %><li><b>Best Water Feature to Fish:</b> <%= @fishing_report.best_water_type %></li><% end %>
          <% if @fishing_report.advice && @fishing_report.advice != '' %><li><b>Advice: </b><%= @fishing_report.advice %></li><% end %>
          <% if @fishing_report.other_notes && @fishing_report.other_notes != '' %><li><b>Other Notes:</b> <%= @fishing_report.other_notes %></li><% end %>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/flies/_fly.html.erb
<li id="fly-<%= fly.id %>">
  <% if fly.name && fly.name != '' %><b>Name:</b> <%= fly.name %> - <% end %>
  <% if fly.fly_type && fly.fly_type != '' %><b>Type:</b> <%= fly.fly_type %> - <% end %>
  <% if fly.setup && fly.setup != '' %><b>Setup:</b> <%= fly.setup %> - <% end %>
  <% if fly.size && fly.size != '' %><b>Size:</b> <%= fly.size %> - <% end %>
  <b>Self-tied:</b> <%= fly.tied_yourself ? "Yes" : "No" %>
</li>

app/views/hatches/_hatch.html.erb
<li id="hatch-<%= hatch.id %>">
  <% if hatch.insect_type && hatch.insect_type != '' %><b>Insect Type:</b> <%= hatch.insect_type %> - <% end %>
  <% if hatch.time_of_day && hatch.time_of_day != '' %><b>Time of Day:</b> <%= hatch.time_of_day %> - <% end %>
  <% if hatch.description && hatch.description != '' %><b>Description:</b> <%= hatch.description %> <% end %>
</li>

app/views/users/edit.html.erb
<%= form_for (current_user) do |f| %>
  <h1> About Me </h1>
  <div class="form-group">
    <%= f.text_area :about_me, rows: 8, class: 'form-control', placeholder: "Story" %>
   </div>
   <%= f.submit "Save", class: 'btn btn-success' %>
<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.username) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.username %>
      </h1>
    </section>
  </aside>
  <div class='stats'>
    <div class='row'>
        <div class='stat col-md-4'>Fish Caught <br><b><%= @user.fish.count %></b></div>
        <div class='stat col-md-4'>Days Fished <br><b><%= @user.fishing_reports.count %></b></div>
      <div class='stat col-md-4'>Locations Fished <br><b><%= Rails.env.development? ? @user.fishing_reports.group(:location).length : @user.fishing_reports.distinct.count(:location) %></b></div>
    </div>
    </div>

    <div class='about-me'>
      <h2>About Me</h2>
      <%= @user.about_me %>
       <% if current_user = @user %><%= link_to 'Edit', edit_user_path(current_user), class: 'edit-link' %><% end %>
    </div>

    <% if @user.fishing_reports.any? %>
      <h2>Fishing Reports</h2>
      <ol class="fishing_reports">
        <%= render @fishing_reports %>
      </ol>
    <% end %>
</div>

app/views/welcome/index.html.erb
</div>
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron" id="main-jumbotron">
  <div class="container">
    <div class="row">
      <div class="col-md-7">
        <h1 class="white-text">Open Waters</h1>
         <p class="white-text">Record your fly fishing experiences and share them with the world!</p>
      </div>
      <% if !current_user %>
      <div class="col-md-5">
            <br>
            <%= form_for(:user, url: registration_path(:user)) do |f| %>
              <div class="form-group">
                <%= f.text_field :username, class: 'form-control', placeholder: "Enter Username" %>
              </div>
              <div class="form-group">
                <%= f.email_field :email, class: 'form-control', placeholder: "Enter Email" %>
              </div>
              <div class="form-group">
                <%= f.password_field :password, class: 'form-control', placeholder: "Enter Password" %>
              </div>
              <div class="form-group">
                <%= f.submit "Sign up for TripSharers", class: 'btn btn-primary btn-lg col-md-12' %>
              </div>
              <div class="form-group">
              </div>
            <% end %>
          <% end %>
      </div>
    </div>
  </div>
</div>
<container>