config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  get 'welcome/index'
  resources :users do
    resources :fishing_reports
  end
  root to: 'welcome#index'
end

app/models/fish.rb
class Fish < ActiveRecord::Base
  belongs_to :user
  belongs_to :fishing_report
  belongs_to :fly
end

app/models/fishing_report.rb
class FishingReport < ActiveRecord::Base
  belongs_to :user
  has_many :flies, dependent: :destroy
  has_many :fish
  has_many :hatches, dependent: :destroy
  validates :user_id, presence: true
  validates :date, presence: true
  validates :title, presence: true

  default_scope -> { order(date: :desc) }

  accepts_nested_attributes_for :fish, reject_if: :all_blank
  accepts_nested_attributes_for :flies, reject_if: :all_blank  
  accepts_nested_attributes_for :hatches, reject_if: :all_blank

end

app/models/fly.rb
class Fly < ActiveRecord::Base
  belongs_to :user
  belongs_to :fishing_report
  has_many :fish
end

app/models/hatch.rb
class Hatch < ActiveRecord::Base
  belongs_to :user
  belongs_to :fishing_report
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,
         :validatable, :confirmable
  has_many :fishing_reports, dependent: :destroy
  has_many :flies, dependent: :destroy
  has_many :fish, dependent: :destroy
  has_many :hatches, dependent: :destroy

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    user_path(current_user)
  end
end

app/controllers/fish_controller.rb
class FishController < ApplicationController
end

app/controllers/flies_controller.rb
class FliesController < ApplicationController
end

app/controllers/hatches_controller.rb
class HatchesController < ApplicationController
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  before_filter :configure_permitted_parameters

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up).push(:username)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @fishing_reports = @user.fishing_reports.all
  end

  def update
    if current_user.update_attributes(user_params)
     flash[:notice] = "User information updated"
   else
     flash[:error] = "Invalid user information"
   end
    redirect_to user_path
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :about_me)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fish_helper.rb
module FishHelper
end

app/helpers/fishing_report_helper.rb
module FishingReportHelper
end

app/helpers/flies_helper.rb
module FliesHelper
end

app/helpers/form_helper.rb
module FormHelper
  def setup_fishing_report(fishing_report)
    3.times { fishing_report.hatches.build }
    3.times { fishing_report.flies.build }
    3.times { fishing_report.fish.build }
    fishing_report
  end
end

app/helpers/hatches_helper.rb
module HatchesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?size=#{size}"
    link_to image_tag(gravatar_url, alt: user.username, class: "gravatar"), 'https://en.gravatar.com/emails/', target: '_blank'
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tripsharers</title>
  <%= stylesheet_link_tag    'application', params[:controller], media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'shared/navbar' %>
<%= render 'shared/flash_message' %>



  <div class='container'>
    <%= yield %>
  </div>
   
   <%= debug(params) if Rails.env.development? %>

</body>
</html>

app/views/shared/_flash_message.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success flash-notice">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:notice] %>
  </div>
<% elsif flash[:error] %>
  <div class="alert alert-danger flash-notice">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:error] %>
  </div>
<% elsif flash[:alert] %>
  <div class="alert alert-warning flash-notice">
    <button type="button" class="close" data-dismiss="alert">&times;</button>
    <%= flash[:alert] %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if current_user %>
        <%= link_to "Open Waters", user_path(current_user), class: "navbar-brand white-text"  %>
      <% else %>
        <%= link_to "Open Waters", root_path, class: "navbar-brand white-text"  %>
      <% end %>
    </div>

    <% if current_user %>
      <% button_html = '<button type="button" class="btn btn-default btn-lg"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span></button>'.html_safe %>
      <form class="navbar-form navbar-right login-blurb">
        <%= link_to button_html, new_user_fishing_report_path(current_user) %>
        <%= gravatar_for(current_user) %>
        <div class="btn-group">
          <button type="button" class="btn btn-primary dropdown-toggle btn-lg" data-toggle="dropdown" aria-expanded="false">
            <%= current_user.username %> <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to "Home", current_user %></li>
            <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
            <li class="divider"></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </div>
      </form>

    <% else %>
      <%= form_for(:user, url: session_path(:user), html: {class: "navbar-form navbar-right"}) do |f| %>
         <div class="form-group">
          <%= f.email_field :email, class: 'form-control', placeholder: "Email" %>
        </div>
        <div class="form-group">
          <%= f.password_field :password, class: 'form-control', placeholder: "Password" %>
        </div>
        <%= f.submit "Sign in", class: 'btn btn-success' %>
      <% end %>
    <% end %>

  </div>
</nav>